In [2]:
from sklearn.datasets import load_files
import pandas as pd

# malaylam and tamil file is combined in excel and sorted ascedning by column Tweet so that tweets from both language got mixed

In [3]:
Mal_Tam_data=pd.read_excel("Malayalam + Tamil.xlsx" , header=None)

In [4]:
Mal_Tam_data[20:30]

            0                                                  1    2
20  TA_HL1013  ( indha award function la munnadi seat la unka...  OFF
21   TA_TW850  ***mmala Silent ah Navundhuru Wanted varadha U...  NOT
22  TA_TW2408  *Ladies...when he tells you....shake what your...  OFF
23   TA_TW586  *listening to havana* appa - "enna paatu kekra...  NOT
24  MA_YT3007  *sangappifalk*um *moori*galkum palaozum ithine...  OFF
25  MA_YT2450  , cashine vendi ningal mathathe upayogichu, or...  OFF
26  TA_HL1012  .. chai ipdila pesadhinga appangra sthanam chi...  NOT
27  TA_TW6109  .. Yaaru @USER sir ah.. Idha ellam paaka nalla...  NOT
28   TA_TW956  .. Yaaru @USER sir ah.. Idha ellam paaka nalla...  NOT
29  MA_YT2726  ... pala pala karyangalil.. self financing.. c...  NOT

In [5]:
Mal_Tam_data[4020:4030]

              0                                                  1    2
4020  TA_TW6403  Ellarum Saptacha ..??? *** : Yen Sapadu Vangi ...  NOT
4021  MA_YT3006  ellarum swandam mathathil vishwasikkunnu.. por...  NOT
4022   TA_HL324  ellarum veruthutinga... ha ha ha.... enakkum n...  NOT
4023   TA_HL325  ellarum wrk pannanumthan slirukanga so athanal...  NOT
4024  MA_YT2898  ellathilum negative kanunna malayalikalk ninan...  NOT
4025  MA_YT1927  Ellathinem oru roomil pootiyititt coronaye ket...  OFF
4026  MA_YT3995  Ellavarkum avrde sundaryamind...inganeparayan ...  NOT
4027  MA_YT3382  ellavarudem perokke marannu poyi eni ellam ran...  NOT
4028  MA_YT2303  Ellavarum dislike cheyyu... Ee pezhakale YouTu...  OFF
4029  MA_YT2269                    Ellavarum kundiyillotta nokkiye  OFF

In [6]:
Mal_Tam_data=Mal_Tam_data.rename(columns={0:'ID', 1:'Tweets', 2:'Labels'})

In [7]:
import regex
import re
import numpy as np

In [8]:
labels,counts=np.unique(Mal_Tam_data['Labels'],return_counts=True)
print(labels,counts)

['Labels' 'NOT' 'OFF' 'OFf' 'not'] [   1 4066 3932    1    1]

In [9]:
lab=Mal_Tam_data['Labels']
lab

0       OFF
1       NOT
2       NOT
3       OFF
4       NOT
       ...
7996    OFF
7997    OFF
7998    OFF
7999    NOT
8000    OFF
Name: Labels, Length: 8001, dtype: object

In [10]:
low_lab=lab.str.lower()
low_lab

0       off
1       not
2       not
3       off
4       not
       ...
7996    off
7997    off
7998    off
7999    not
8000    off
Name: Labels, Length: 8001, dtype: object

In [11]:
Lowlabels=pd.DataFrame(low_lab)
Lowlabels.columns=['Lowlabels']
Lowlabels

     Lowlabels
0          off
1          not
2          not
3          off
4          not
...        ...
7996       off
7997       off
7998       off
7999       not
8000       off

[8001 rows x 1 columns]

In [12]:
Mal_Tam_data=pd.concat([Mal_Tam_data, Lowlabels], axis=1)
Mal_Tam_data

,ID,Tweets,Labels,Lowlabels
0,TA_TW2403,#TAG #TAG elumban fans vaai punda athigam than...,OFF,off
1,TA_TW1685,#TAG @USER vandha valiya marakama ellaa stage ...,NOT,not
2,TA_TW429,"#TAG After hearing the song,thumbi thullucho n...",NOT,not
3,TA_TW2404,#TAG andha police naingala thookula podanum......,OFF,off
4,TA_TW656,#TAG Anna post pottu 1Week ku mela aachu ... E...,NOT,not
...,...,...,...,...
7996,MA_YT1700,Yukthivsthathil incest allowed aan,OFF,off
7997,TA_HL1010,yullaa onumayaa podulaiyaa apdiyaa boots triyu...,OFF,off
7998,TA_HL1011,zoola irukka vendiyathulaam paduthula nadikkuthu,OFF,off
7999,MA_YT168,😆😆allam kaayinnu poyi😆😆 Ah motta chettanu ente...,NOT,not
8000,MA_YT1381,NaN,OFF,off

In [13]:
Mal_Tam_data['Lowlabels']=Mal_Tam_data['Lowlabels'].apply(lambda x: 1 if x=="off" else 0)

In [14]:
Mal_Tam_data

,ID,Tweets,Labels,Lowlabels
0,TA_TW2403,#TAG #TAG elumban fans vaai punda athigam than...,OFF,1
1,TA_TW1685,#TAG @USER vandha valiya marakama ellaa stage ...,NOT,0
2,TA_TW429,"#TAG After hearing the song,thumbi thullucho n...",NOT,0
3,TA_TW2404,#TAG andha police naingala thookula podanum......,OFF,1
4,TA_TW656,#TAG Anna post pottu 1Week ku mela aachu ... E...,NOT,0
...,...,...,...,...
7996,MA_YT1700,Yukthivsthathil incest allowed aan,OFF,1
7997,TA_HL1010,yullaa onumayaa podulaiyaa apdiyaa boots triyu...,OFF,1
7998,TA_HL1011,zoola irukka vendiyathulaam paduthula nadikkuthu,OFF,1
7999,MA_YT168,😆😆allam kaayinnu poyi😆😆 Ah motta chettanu ente...,NOT,0
8000,MA_YT1381,NaN,OFF,1

In [15]:
msg=Mal_Tam_data['Tweets']

In [16]:
# Removing all emojis from tweets by using the emojis code 
msg_emoj=msg.str.replace(r'[(\U0001F600-\U0001F92F|\U0001F300-\U0001F5FF|\U0001F680-\U0001F6FF|\U0001F190-\U0001F1FF|\U00002702-\U000027B0|\U0001F926-\U0001FA9F|\u200d|\u2640-\u2642|\u2600-\u2B55|\u23cf|\u23e9|\u231a|\ufe0f)]+','')
msg_emoj[3830:3840]

3830                 e pottanu vote cheyunavare thallanam
3831    e puliyaadimon aanu vargeya vadhi thayoli kuth...
3832    E rema ashiaq,abu aanu bhavanye rashikkan nilk...
3833              E sadika arannu enike epozhum doubt anu
3834    E sambhavam mukkiA madhAmangalkethire case edu...
3835    E sangi congi pongi ennoke paranjal pennint po...
3836                      e thayolik penmakkal onnum ille
3837    E video eduthavan.....................#@$#$$:"...
3838    E...barthavineyum bhariyeneyum odikan arumile....
3839    ea..poallayadeacheakkallea....veacheakaruthe.....
Name: Tweets, dtype: object

In [17]:
# Removing @USER at the start of each tweet
msg_USER_TAG=msg_emoj.str.replace(r"@USER |RT| #TAG", ' ')
#Chceking from tamil dataset whether @USER, @RT and @TAG are removed..?
msg_USER_TAG[1:10]

1    #TAG  vandha valiya marakama ellaa stage la yu...
2    #TAG After hearing the song,thumbi thullucho n...
3    #TAG andha police naingala thookula podanum......
4    #TAG Anna post pottu 1Week ku mela aachu ... E...
5    #TAG censor board team kuda wish panirukanga a...
6    #TAG Enna ba idhu? Ipdi panniputeenga? Poll po...
7    #TAG fuck you Tamilnadu police you and your gu...
8    #TAG Intha ulagathilla romba easyyaana Visayam...
9    #TAG mami returns with tempting hot age analum...
Name: Tweets, dtype: object

In [18]:
#Chceking from Malaylam dataset whether @USER is removed..?
msg_USER_TAG[200:208]

200     Adeiii enna issthunu poda ottagaa paal la tea...
201     Adengappa unaku irukura followers ku inike ne...
202     Adengappa unaku irukura followers ku inike ne...
203     Adengappa. Unaku arivu illanu theriyum. Aana ...
204     adhellam kanake illadha alavuku pathachu.. Se...
205     adhepdi ne sollalam innum 1 r 2 years nu. and...
206     Adhu epidi postpone ... Ne yaarula anna unive...
207     Adhu irukattum andha mangatha la gundan dhan ...
Name: Tweets, dtype: object

In [142]:
# Encoding  ðŸ˜ðŸ˜ & many other symbols to ASCII; so that those r removed from tweets. 
# After removal we can see msg is encoded and started with b'
msg_USER_Encod=msg_USER_TAG.str.encode("ascii", "ignore")
msg_USER_Encod[200:208], type(msg_USER_Encod)

(200    b' Adeiii enna issthunu poda ottagaa paal la t...
 201    b' Adengappa unaku irukura followers ku inike ...
 202    b' Adengappa unaku irukura followers ku inike ...
 203    b' Adengappa. Unaku arivu illanu theriyum. Aan...
 204    b' adhellam kanake illadha alavuku pathachu.. ...
 205    b' adhepdi ne sollalam innum 1 r 2 years nu. a...
 206    b' Adhu epidi postpone ... Ne yaarula anna uni...
 207    b' Adhu irukattum andha mangatha la gundan dha...
 Name: Tweets, dtype: object, pandas.core.series.Series)

In [143]:
# Decoding msg to format where we can see b' is removed 
msg_USER_decod=msg_USER_Encod.str.decode(encoding = 'ASCII')
msg_USER_decod[200:208]

200     Adeiii enna issthunu poda ottagaa paal la tea...
201     Adengappa unaku irukura followers ku inike ne...
202     Adengappa unaku irukura followers ku inike ne...
203     Adengappa. Unaku arivu illanu theriyum. Aana ...
204     adhellam kanake illadha alavuku pathachu.. Se...
205     adhepdi ne sollalam innum 1 r 2 years nu. and...
206     Adhu epidi postpone ... Ne yaarula anna unive...
207     Adhu irukattum andha mangatha la gundan dhan ...
Name: Tweets, dtype: object

In [144]:
# Removing digits 
msg_Digit = msg_USER_decod.str.replace(r'[0-9]', ' ')
msg_Digit[7080:7081]

7080       Dei poolu illa thevidiya Paiyan poi ungomma...
Name: Tweets, dtype: object

In [145]:
# Removing Special Characters
msg_SpChar = msg_Digit.str.replace(r'[^\w\d\s]', ' ')
print(msg_SpChar[51])

   Moly VALLODATHU NINNUM VALINJU KAYARI VANNITTU KONAKKUNNODA MYRE NINTE THALLAYEYUM PENGALEYUM BHARYAYEYUM KUNDIYUM MULAYUM ADICHU POLICHU KALAYUM NJAN

In [146]:
# Removing  Hyphens & xtra Whitespaces 
msg_Spac = msg_SpChar.str.replace(r'\s+', ' ')
msg_Hyp = msg_Spac.str.replace(r'_','')

In [147]:
# storing msg_spec (i.e. processed data) into dataframe Msg_df
Msg_df=pd.DataFrame(msg_Hyp)
Msg_df.columns=['Msg_with_Stopwords']

In [148]:
# Removing Null values 
Msg_df['Msg_with_Stopwords']=Msg_df['Msg_with_Stopwords'].fillna("")

In [149]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [150]:
# Removing Stop words 
stop_words = set(stopwords.words('english'))

In [151]:
Msg_df['Msg_without_Stopwords']=Msg_df['Msg_with_Stopwords'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [152]:
Msg_df['Msg_without_Stopwords']

0       TAG elumban fans vaai punda athigam suriya ann...
1       TAG vandha valiya marakama ellaa stage la yum ...
2       TAG After hearing song thumbi thullucho nu the...
3       TAG andha police naingala thookula podanum ill...
4       TAG Anna post pottu Week ku mela aachu Enna nu...
                              ...
7996                   Yukthivsthathil incest allowed aan
7997    yullaa onumayaa podulaiyaa apdiyaa boots triyu...
7998     zoola irukka vendiyathulaam paduthula nadikkuthu
7999    allam kaayinnu poyi Ah motta chettanu ente vak...
8000
Name: Msg_without_Stopwords, Length: 8001, dtype: object

In [153]:
# Counting length of each tweet  with stopwords and without stopwords 
Msg_df['Msg_with_Stopwords_Len'] = [len(x.split()) for x in Msg_df['Msg_with_Stopwords'].tolist()]
Msg_df['Msg_without_Stopwords_Len'] = [len(x.split()) for x in Msg_df['Msg_without_Stopwords'].tolist()]

In [154]:
Msg_df

,Msg_with_Stopwords,Msg_without_Stopwords,Msg_with_Stopwords_Len,Msg_without_Stopwords_Len
0,TAG elumban fans vaai punda athigam than suri...,TAG elumban fans vaai punda athigam suriya ann...,12,11
1,TAG vandha valiya marakama ellaa stage la yum...,TAG vandha valiya marakama ellaa stage la yum ...,13,13
2,TAG After hearing the song thumbi thullucho n...,TAG After hearing song thumbi thullucho nu the...,28,20
3,TAG andha police naingala thookula podanum il...,TAG andha police naingala thookula podanum ill...,33,33
4,TAG Anna post pottu Week ku mela aachu Enna n...,TAG Anna post pottu Week ku mela aachu Enna nu...,25,25
...,...,...,...,...
7996,Yukthivsthathil incest allowed aan,Yukthivsthathil incest allowed aan,4,4
7997,yullaa onumayaa podulaiyaa apdiyaa boots triyu...,yullaa onumayaa podulaiyaa apdiyaa boots triyu...,7,7
7998,zoola irukka vendiyathulaam paduthula nadikkuthu,zoola irukka vendiyathulaam paduthula nadikkuthu,5,5
7999,allam kaayinnu poyi Ah motta chettanu ente vak...,allam kaayinnu poyi Ah motta chettanu ente vak...,11,11
8000,,,0,0

In [155]:
# Concatinating original dataframe i.e. Mal_Tam_data and modified dataframes i.e. Msg_df into final_Data
final_Data=pd.concat([Msg_df, Mal_Tam_data], axis=1)
final_Data

,Msg_with_Stopwords,Msg_without_Stopwords,Msg_with_Stopwords_Len,Msg_without_Stopwords_Len,ID,Tweets,Labels,Lowlabels
0,TAG elumban fans vaai punda athigam than suri...,TAG elumban fans vaai punda athigam suriya ann...,12,11,TA_TW2403,#TAG #TAG elumban fans vaai punda athigam than...,OFF,1
1,TAG vandha valiya marakama ellaa stage la yum...,TAG vandha valiya marakama ellaa stage la yum ...,13,13,TA_TW1685,#TAG @USER vandha valiya marakama ellaa stage ...,NOT,0
2,TAG After hearing the song thumbi thullucho n...,TAG After hearing song thumbi thullucho nu the...,28,20,TA_TW429,"#TAG After hearing the song,thumbi thullucho n...",NOT,0
3,TAG andha police naingala thookula podanum il...,TAG andha police naingala thookula podanum ill...,33,33,TA_TW2404,#TAG andha police naingala thookula podanum......,OFF,1
4,TAG Anna post pottu Week ku mela aachu Enna n...,TAG Anna post pottu Week ku mela aachu Enna nu...,25,25,TA_TW656,#TAG Anna post pottu 1Week ku mela aachu ... E...,NOT,0
...,...,...,...,...,...,...,...,...
7996,Yukthivsthathil incest allowed aan,Yukthivsthathil incest allowed aan,4,4,MA_YT1700,Yukthivsthathil incest allowed aan,OFF,1
7997,yullaa onumayaa podulaiyaa apdiyaa boots triyu...,yullaa onumayaa podulaiyaa apdiyaa boots triyu...,7,7,TA_HL1010,yullaa onumayaa podulaiyaa apdiyaa boots triyu...,OFF,1
7998,zoola irukka vendiyathulaam paduthula nadikkuthu,zoola irukka vendiyathulaam paduthula nadikkuthu,5,5,TA_HL1011,zoola irukka vendiyathulaam paduthula nadikkuthu,OFF,1
7999,allam kaayinnu poyi Ah motta chettanu ente vak...,allam kaayinnu poyi Ah motta chettanu ente vak...,11,11,MA_YT168,😆😆allam kaayinnu poyi😆😆 Ah motta chettanu ente...,NOT,0
8000,,,0,0,MA_YT1381,NaN,OFF,1

In [156]:
# Dropping the columns Tweets and ID
final_Data=final_Data.drop(['Tweets', 'ID', 'Labels'], axis=1)
final_Data

,Msg_with_Stopwords,Msg_without_Stopwords,Msg_with_Stopwords_Len,Msg_without_Stopwords_Len,Lowlabels
0,TAG elumban fans vaai punda athigam than suri...,TAG elumban fans vaai punda athigam suriya ann...,12,11,1
1,TAG vandha valiya marakama ellaa stage la yum...,TAG vandha valiya marakama ellaa stage la yum ...,13,13,0
2,TAG After hearing the song thumbi thullucho n...,TAG After hearing song thumbi thullucho nu the...,28,20,0
3,TAG andha police naingala thookula podanum il...,TAG andha police naingala thookula podanum ill...,33,33,1
4,TAG Anna post pottu Week ku mela aachu Enna n...,TAG Anna post pottu Week ku mela aachu Enna nu...,25,25,0
...,...,...,...,...,...
7996,Yukthivsthathil incest allowed aan,Yukthivsthathil incest allowed aan,4,4,1
7997,yullaa onumayaa podulaiyaa apdiyaa boots triyu...,yullaa onumayaa podulaiyaa apdiyaa boots triyu...,7,7,1
7998,zoola irukka vendiyathulaam paduthula nadikkuthu,zoola irukka vendiyathulaam paduthula nadikkuthu,5,5,1
7999,allam kaayinnu poyi Ah motta chettanu ente vak...,allam kaayinnu poyi Ah motta chettanu ente vak...,11,11,0
8000,,,0,0,1

In [157]:
# splitting the dataset into train=70% & test=30% where X=final_Data.Msg_without_Stopwords & Y=final_Data.Labels
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(final_Data.Msg_without_Stopwords, final_Data.Lowlabels,  random_state=40, test_size=0.3)

In [158]:
len(X_train), len(y_train), len(X_test), len(y_test)

(5600, 5600, 2401, 2401)

In [159]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(analyzer='word', lowercase=True, ngram_range=(1,6))
X=tfidf.fit_transform(X_train)
Y=y_train
tfidf

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 6), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [160]:
char_tfidf=TfidfVectorizer(analyzer='char', lowercase=True, ngram_range=(1, 8))
X_char=char_tfidf.fit_transform(X_train) 
char_tfidf

TfidfVectorizer(analyzer='char', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 8), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [161]:
# No of features extracted 
len(tfidf.get_feature_names()), len(char_tfidf.get_feature_names())

(282975, 862753)

In [162]:
tfidf.get_feature_names()

['aa',
 'aa aala',
 'aa aala thanna',
 'aa aala thanna alla',
 'aa aala thanna alla matruka',
 'aa aala thanna alla matruka aakkunnathu',
 'aa accountinte',
 'aa accountinte aalu',
 'aa accountinte aalu thanne',
 'aa accountinte aalu thanne annu',
 'aa accountinte aalu thanne annu trolling',
 'aa adhamanaya',
 'aa adhamanaya nadanodu',
 'aa adhamanaya nadanodu paranhittu',
 'aa adhamanaya nadanodu paranhittu kariyamolla',
 'aa adhamanaya nadanodu paranhittu kariyamolla sir',
 'aa adikkan',
 'aa adikkan pattu',
 'aa adikkan pattu alllakil',
 'aa adikkan pattu alllakil oru',
 'aa adikkan pattu alllakil oru million',
 'aa adisthanathil',
 'aa adisthanathil pooran',
 'aa adisthanathil pooran security',
 'aa adisthanathil pooran security ella',
 'aa adisthanathil pooran security ella penungalem',
 'aa athellame',
 'aa athellame solli',
 'aa athellame solli thitra',
 'aa athellame solli thitra ungamma',
 'aa athellame solli thitra ungamma koothi',
 'aa avar',
 'aa avar orupad',
 'aa avar orupad perund',
 'aa avar orupad perund jagathi',
 'aa avar orupad perund jagathi chettan',
 'aa baalayumayi',
 'aa baalayumayi ulla',
 'aa baalayumayi ulla oru',
 'aa baalayumayi ulla oru interview',
 'aa baalayumayi ulla oru interview kandu',
 'aa bedinadiyale',
 'aa bedinadiyale alde',
 'aa bedinadiyale alde mudiyum',
 'aa bedinadiyale alde mudiyum sama',
 'aa bedinadiyale alde mudiyum sama alle',
 'aa beef',
 'aa beef roast',
 'aa beef roast chicken',
 'aa beef roast chicken roast',
 'aa beef roast chicken roast nn',
 'aa casaba',
 'aa casaba movie',
 'aa casaba movie le',
 'aa casaba movie le police',
 'aa casaba movie le police kaari',
 'aa cinema',
 'aa cinema moshamaakatte',
 'aa cinema moshamaakatte nallathaakatte',
 'aa cinema moshamaakatte nallathaakatte athu',
 'aa cinema moshamaakatte nallathaakatte athu kayinjit',
 'aa da',
 'aa da ne',
 'aa da un',
 'aa da un english',
 'aa da un english pundai',
 'aa da un english pundai la',
 'aa dhan',
 'aa dhan iruku',
 'aa dhan iruku dha',
 'aa dhan iruku dha best',
 'aa duplicate',
 'aa duplicate vangunnavalude',
 'aa duplicate vangunnavalude original',
 'aa duplicate vangunnavalude original video',
 'aa film',
 'aa film um',
 'aa film um ethum',
 'aa film um ethum vech',
 'aa film um ethum vech nml',
 'aa film und',
 'aa gathi',
 'aa gathi neerajinu',
 'aa gathi neerajinu varathirikkan',
 'aa gathi neerajinu varathirikkan nokkandath',
 'aa gathi neerajinu varathirikkan nokkandath cinema',
 'aa gaya',
 'aa gaya evlo',
 'aa gaya evlo per',
 'aa gaya evlo per venalum',
 'aa gaya evlo per venalum vanga',
 'aa indarw',
 'aa indarw edukunavalude',
 'aa indarw edukunavalude dres',
 'aa irukaanga',
 'aa irukan',
 'aa irukan ithukumela',
 'aa irukan ithukumela avana',
 'aa irukan ithukumela avana pathi',
 'aa irukan ithukumela avana pathi peysurathuku',
 'aa irukanga',
 'aa irukanga ipdilam',
 'aa irukanga ipdilam panna',
 'aa irukanga ipdilam panna bby',
 'aa irukanga ipdilam panna bby kku',
 'aa irukku',
 'aa ishtam',
 'aa ithu',
 'aa ithu polulavnmaar',
 'aa ithu polulavnmaar rahnaye',
 'aa ithu polulavnmaar rahnaye kuttam',
 'aa ithu polulavnmaar rahnaye kuttam parayumbol',
 'aa kaatuthu',
 'aa kaatuthu konjam',
 'aa kaatuthu konjam decent',
 'aa kaatuthu konjam decent aa',
 'aa kaatuthu konjam decent aa pesa',
 'aa kalaye',
 'aa kalaye kola',
 'aa kalaye kola yaaki',
 'aa kannil',
 'aa kannil ang',
 'aa kannil ang kand',
 'aa kannil ang kand pokum',
 'aa karumbi',
 'aa karumbi aavum',
 'aa kasilu',
 'aa kasilu adutha',
 'aa kasilu adutha padameukkan',
 'aa kochine',
 'aa kochine video',
 'aa kochine video edknad',
 'aa kochine video edknad man',
 'aa kochine video edknad man ann',
 'aa ku',
 'aa ku romba',
 'aa ku romba kastam',
 'aa kunji',
 'aa kunji kochinte',
 'aa kunji kochinte munnil',
 'aa kunji kochinte munnil aano',
 'aa kunji kochinte munnil aano thalle',
 'aa kunjine',
 'aa kunjine kurich',
 'aa kunjine kurich chinthicha',
 'aa kunjine kurich chinthicha karyam',
 'aa kuppa',
 'aa kuppa thottiyil',
 'aa kuppa thottiyil veesittu',
 'aa kuppa thottiyil veesittu poguthey',
 'aa kuppa thottiyil veesittu poguthey antha',
 'aa kutavali',
 'aa kutavali jailil',
 'aa kutavali jailil sugikukayanallo',
 'aa kutavali jailil sugikukayanallo evar',
 'aa kutavali jailil sugikukayanallo evar beautiparlour',
 'aa kuttikalude',
 'aa kuttikalude karachil',
 'aa kuttikalude karachil kandappo',
 'aa kuttinnea',
 'aa kuttinnea kond',
 'aa kuttinnea kond paranjubcheyiurl',
 'aa kuttinnea kond paranjubcheyiurl avall',
 'aa kuttinnea kond paranjubcheyiurl avall shariramm',
 'aa kutty',
 'aa kutty nannayi',
 'aa kutty nannayi varakunund',
 'aa kutty nannayi varakunund learn',
 'aa kutty nannayi varakunund learn face',
 'aa kuttykalude',
 'aa kuttykalude kaaryam',
 'aa kuttykalude kaaryam orkkumbol',
 'aa kuttykalude kaaryam orkkumbol sankadam',
 'aa kuttykalude kaaryam orkkumbol sankadam thonnunnu',
 'aa mathathile',
 'aa mathathile pole',
 'aa mathathile pole chaakil',
 'aa mathathile pole chaakil pothinju',
 'aa mathathile pole chaakil pothinju erikkano',
 'aa mic',
 'aa mic onnu',
 'aa mic onnu url',
 'aa mic onnu url vangaan',
 'aa mon',
 'aa mon kurach',
 'aa mon kurach koodi',
 'aa mon kurach koodi valarumbo',
 'aa mon kurach koodi valarumbo avnumayi',
 'aa moonjiya',
 'aa moonjiya idavela',
 'aa moonjiya idavela baabune',
 'aa moonjiya idavela baabune url',
 'aa moonjiya idavela baabune url adhyam',
 'aa moviyil',
 'aa moviyil chanse',
 'aa moviyil chanse kittiyirunnel',
 'aa moviyil chanse kittiyirunnel evalithoke',
 'aa moviyil chanse kittiyirunnel evalithoke parayoo',
 'aa mugathu',
 'aa mugathu varanilla',
 'aa naarikal',
 'aa naarikal aanu',
 'aa naarikal aanu mohanlal',
 'aa naarikal aanu mohanlal nedumudi',
 'aa naarikal aanu mohanlal nedumudi priyadhrshan',
 'aa nan',
 'aa nan romba',
 'aa nan romba nallavan',
 'aa nan romba nallavan aana',
 'aa nan romba nallavan aana unna',
 'aa nariye',
 'aa nariye verupp',
 'aa nariye verupp aanu',
 'aa nariye verupp aanu njn',
 'aa nariye verupp aanu njn avante',
 'aa news',
 'aa news channel',
 'aa news channel oru',
 'aa news channel oru interview',
 'aa news channel oru interview undayarunu',
 'aa odukathe',
 'aa odukathe negative',
 'aa offical',
 'aa offical ah',
 'aa offical ah release',
 'aa offical ah release panala',
 'aa offical ah release panala user',
 'aa oola',
 'aa oola cow',
 'aa oola cow swameene',
 'aa oola cow swameene enthina',
 'aa oola cow swameene enthina da',
 'aa oru',
 'aa oru sailiyil',
 'aa oru sailiyil thanne',
 'aa oru sailiyil thanne para',
 'aa paathu',
 'aa paathu thaa',
 'aa paathu thaa bro',
 'aa paathu thaa bro movies',
 'aa paathu thaa bro movies laa',
 'aa pandra',
 'aa pandra porama',
 'aa pandra porama pidichava',
 'aa pandra porama pidichava birthday',
 'aa pandra porama pidichava birthday wish',
 'aa panna',
 'aa panna enit',
 'aa panna enit ipo',
 'aa panna enit ipo nallavane',
 'aa panna enit ipo nallavane pole',
 'aa pannide',
 'aa pannide chanel',
 'aa pannide chanel subscribe',
 'aa pannide chanel subscribe cheythitte',
 'aa pannide chanel subscribe cheythitte illa',
 'aa pannitu',
 'aa pannitu irukka',
 'aa pannitu irukka naan',
 'aa pannitu irukka naan yaaruku',
 'aa pannitu irukka naan yaaruku birthday',
 'aa paranja',
 'aa paranja elimatham',
 'aa paranja elimatham kanichu',
 'aa paranja elimatham kanichu jeevikunavaril',
 'aa paranja elimatham kanichu jeevikunavaril oral',
 'aa parasyathilu',
 'aa parasyathilu ninn',
 'aa parasyathilu ninn matre',
 'aa parasyathilu ninn matre kitoo',
 'aa parasyathilu ninn matre kitoo nammal',
 'aa pattam',
 'aa pattam vere',
 'aa pattam vere aarkkum',
 'aa pattam vere aarkkum kodukkaruth',
 'aa pattam vere aarkkum kodukkaruth bro',
 'aa pavam',
 'aa pavam kochine',
 'aa pavam kochine konnu',
 'aa pavam kochine konnu kalayaruthu',
 'aa pavam kochine konnu kalayaruthu ennu',
 'aa pavathinu',
 'aa pavathinu matram',
 'aa pavathinu matram peru',
 'aa pavathinu matram peru dhosham',
 'aa pavathinu matram peru dhosham jeevikanulla',
 'aa payyan',
 'aa payyan kanjavanennu',
 'aa payyan kanjavanennu paranju',
 'aa payyan kanjavanennu paranju thalli',
 'aa payyan kanjavanennu paranju thalli avanayirunnu',
 'aa payyante',
 'aa payyante jeevitham',
 'aa payyante jeevitham thulakallle',
 'aa payyante jeevitham thulakallle please',
 'aa payyante jeevitham thulakallle please ayyal',
 'aa peedakaneyanu',
 'aa peedakaneyanu orma',
 'aa peedakaneyanu orma varunnath',
 'aa penkuttikk',
 'aa penkuttikk ariyam',
 'aa penkuttiye',
 'aa penkuttiye polum',
 'aa penkuttiye polum puchikkunnu',
 'aa penkuttiye polum puchikkunnu avalde',
 'aa penkuttiye polum puchikkunnu avalde niram',
 'aa periyarism',
 'aa periyarism panadha',
 'aa periyarism panadha ne',
 'aa periyarism panadha ne pesardhu',
 'aa periyarism panadha ne pesardhu oru',
 'aa perukettapozhe',
 'aa perukettapozhe atha',
 'aa perukettapozhe atha orma',
 'aa perukettapozhe atha orma vannathu',
 'aa pesa',
 'aa pesa palagunga',
 'aa pesa palagunga ngra',
 'aa pesa palagunga ngra sonnar',
 'aa poorathiyude',
 'aa poorathiyude kundikk',
 'aa poorathiyude kundikk valla',
 'aa poorathiyude kundikk valla choriyum',
 'aa poorathiyude kundikk valla choriyum url',
 'aa poori',
 'aa poori mathramala',
 'aa poori mathramala pange',
 'aa poori mathramala pange vereyum',
 'aa poori mathramala pange vereyum kore',
 'aa poorinoodu',
 'aa poorinoodu njngl',
 'aa poorinoodu njngl endu',
 'aa poorinoodu njngl endu koode',
 'aa poorinoodu njngl endu koode url',
 'aa poorinte',
 'aa poorinte samskaaram',
 'aa poorinte samskaaram cheta',
 'aa positionil',
 'aa positionil ethunnathanu',
 'aa positionil ethunnathanu nammale',
 'aa positionil ethunnathanu nammale vijayam',
 'aa pretham',
 'aa pretham aarann',
 'aa pretham aarann manssilaayo',
 'aa pretham aarann manssilaayo namma',
 'aa pretham aarann manssilaayo namma kure',
 'aa question',
 'aa question chodikuna',
 'aa question chodikuna penninnde',
 'aa question chodikuna penninnde monda',
 'aa question chodikuna penninnde monda pona',
 'aa respect',
 'aa respect epo',
 'aa respect epo ellathe',
 'aa respect epo ellathe aayi',
 'aa samayathokke',
 'aa samayathokke kitye',
 'aa samayathokke kitye ipo',
 'aa samayathokke kitye ipo pinne',
 'aa samayathokke kitye ipo pinne kilavi',
 'aa samsarashailyil',
 'aa samyath',
 'aa samyath kochin',
 'aa samyath kochin haneefkade',
 'aa samyath kochin haneefkade troll',
 'aa samyath kochin haneefkade troll njan',
 'aa sthreeyude',
 'aa sthreeyude manasika',
 'aa sthreeyude manasika nila',
 'aa sthreeyude manasika nila angane',
 'aa sthreeyude manasika nila angane aanennu',
 'aa supports',
 'aa supports ellam',
 'aa supports ellam koodi',
 'aa supports ellam koodi pongaala',
 'aa supports ellam koodi pongaala ittu',
 'aa tadiyan',
 'aa tadiyan mukam',
 'aa tadiyan mukam potunnate',
 'aa tadiyan mukam potunnate antinaa',
 'aa tadiyan mukam potunnate antinaa avana',
 'aa tane',
 'aa tane nenga',
 'aa tane nenga parthu',
 'aa tane nenga parthu ra',
 'aa tendiku',
 'aa tendiku lokam',
 'aa tendiku lokam mottam',
 'aa tendiku lokam mottam pennungal',
 'aa tendiku lokam mottam pennungal anello',
 'aa thaan',
 'aa thaan start',
 'aa thaan start pannirukken',
 'aa thaan start pannirukken innum',
 'aa thaan start pannirukken innum neraya',
 'aa thattippil',
 'aa thattippil ashiqe',
 'aa thattippil ashiqe abhuvum',
 'aa thattippil ashiqe abhuvum onnu',
 'aa thattippil ashiqe abhuvum onnu kattu',
 'aa thirumondha',
 'aa thirumondha kandal',
 'aa thirumondha kandal annathe',
 'aa thirumondha kandal annathe divasam',
 'aa thirumondha kandal annathe divasam pokka',
 'aa torture',
 'aa torture okke',
 'aa torture okke karannam',
 'aa torture okke karannam aagum',
 'aa torture okke karannam aagum ivanmaru',
 'aa vaakke',
 'aa vaakke arhikkunnullu',
 'aa vamshashudhi',
 'aa vamshashudhi marannu',
 'aa vamshashudhi marannu poyi',
 'aa vamshashudhi marannu poyi kaanum',
 'aa vdo',
 'aa vdo upload',
 'aa vdo upload cheythute',
 'aa vdo upload cheythute ithilum',
 'aa vdo upload cheythute ithilum kooduthal',
 'aa verudhe',
 'aa verudhe thallal',
 'aa verudhe thallal aanu',
 'aa video',
 'aa video edutha',
 'aa video edutha myrane',
 'aa video edutha myrane chevikkallinu',
 'aa video edutha myrane chevikkallinu orennom',
 'aa video kke',
 'aa video kke ella',
 'aa video kke ella ennaalum',
 'aa video kke ella ennaalum parayaathirikkaan',
 'aa vrithiketta',
 'aa vrithiketta pardha',
 'aa vrithiketta pardha thidunathilum',
 'aa vrithiketta pardha thidunathilum nallath',
 'aa vrithiketta pardha thidunathilum nallath egane',
 'aaa',
 'aaa aaa',
 'aaa aaa myre',
 'aaa aaa myre paraja',
 'aaa aaa myre paraja mathi',
 'aaa artina',
 'aaa artina kuriche',
 'aaa artina kuriche onnum',
 'aaa artina kuriche onnum nigalke',
 'aaa artina kuriche onnum nigalke parayan',
 'aaa ath',
 'aaa ath avrde',
 'aaa ath avrde phonel',
 'aaa ath avrde phonel work',
 'aaa ath avrde phonel work kanan',
 'aaa corona',
 'aaa corona issue',
 'aaa corona issue erukku',
 'aaa corona issue erukku intha',
 'aaa corona issue erukku intha nerathula',
 'aaa corona virus',
 'aaa corona virus ivammare',
 'aaa corona virus ivammare onnum',
 'aaa corona virus ivammare onnum kanunille',
 'aaa dialogue',
 'aaa dialogue delivery',
 'aaa dialogue delivery aaa',
 'aaa dialogue delivery aaa presentation',
 'aaa dialogue delivery aaa presentation adipoli',
 'aaa kadalicha',
 'aaa kadalicha ponna',
 'aaa kadalicha ponna adairadhuku',
 'aaa kadalicha ponna adairadhuku per',
 'aaa kadalicha ponna adairadhuku per kadhal',
 'aaa kedukure',
 'aaa kedukure thayoli',
 'aaa keralam',
 'aaa keralam vittal',
 'aaa keralam vittal neyokhe',
 'aaa keralam vittal neyokhe nthuva',
 'aaa keralam vittal neyokhe nthuva kaniekhune',
 'aaa knaappanmaarde',
 'aaa knaappanmaarde collegela',
 'aaa knaappanmaarde collegela padiche',
 'aaa kundeekude',
 'aaa kundeekude swarnam',
 'aaa kundeekude swarnam varillallo',
 'aaa kundeekude swarnam varillallo ivattangalude',
 'aaa kundeekude swarnam varillallo ivattangalude kaanumbo',
 'aaa mammootty',
 'aaa mammootty enthu',
 'aaa mammootty enthu mudiya',
 'aaa mammootty enthu mudiya murikkunnathu',
 'aaa myre',
 'aaa myre paraja',
 'aaa myre paraja mathi',
 'aaa mythandiyode',
 'aaa mythandiyode onu',
 'aaa mythandiyode onu interview',
 'aaa mythandiyode onu interview chiyanam',
 'aaa mythandiyode onu interview chiyanam appo',
 'aaa naav',
 'aaa naav puzhuth',
 'aaa naav puzhuth chath',
 'aaa naav puzhuth chath poovum',
 'aaa naav puzhuth chath poovum ighanthe',
 'aaa nayinte',
 'aaa nayinte mole',
 'aaa nayinte mole nattukarkk',
 'aaa nayinte mole nattukarkk koduth',
 'aaa nayinte mole nattukarkk koduth nee',
 'aaa paavam',
 'aaa paavam devathaye',
 'aaa paavam devathaye theri',
 'aaa paavam devathaye theri vilipich',
 'aaa paavam devathaye theri vilipich kollunneee',
 'aaa parkkillum',
 'aaa parkkillum beachillum',
 'aaa parkkillum beachillum poyaal',
 'aaa parkkillum beachillum poyaal ningal',
 'aaa parkkillum beachillum poyaal ningal rehanaye',
 'aaa period',
 'aaa period sleeurl',
 'aaa period sleeurl pt',
 'aaa period sleeurl pt anagil',
 'aaa period sleeurl pt anagil happy',
 'aaa pola',
 'aaa pola oombi',
 'aaa pola oombi punda',
 'aaa presentation',
 'aaa presentation adipoli',
 'aaa presentation adipoli iyaalu',
 'aaa presentation adipoli iyaalu serikkum',
 'aaa presentation adipoli iyaalu serikkum kumbidi',
 'aaa revathi',
 'aaa revathi kurach',
 'aaa revathi kurach prayam',
 'aaa revathi kurach prayam ulla',
 'aaa revathi kurach prayam ulla strreee',
 'aaa samskara',
 'aaa samskara samban',
 'aaa samskara samban athayd',
 'aaa samskara samban athayd nindeyokka',
 'aaa samskara samban athayd nindeyokka team',
 'aaa sound',
 'aaa sound kettpol',
 'aaa sound kettpol ah',
 'aaa sound kettpol ah onnu',
 'aaa sound kettpol ah onnu chuttum',
 'aaa sthreekku',
 'aaa sthreekku ivide',
 'aaa sthreekku ivide kuttam',
 'aaa sthreekku ivide kuttam parayunnavarekaal',
 'aaa sthreekku ivide kuttam parayunnavarekaal nalla',
 'aaa thendi',
 'aaa thendi maruku',
 'aaa thendi maruku congress',
 'aaa thendi maruku congress communist',
 'aaa thendi maruku congress communist ithellam',
 'aaa thevidichi',
 'aaa thevidichi moliney',
 'aaa thevidichi moliney okey',
 'aaa thevidichi moliney okey kollanam',
 'aaaa',
 'aaaa evil',
 'aaaa evil eppo',
 'aaaa evil eppo evede',
 'aaaa evil eppo evede oppam',
 'aaaa evil eppo evede oppam ayo',
 'aaaa fathima',
 'aaaa fathima peru',
 'aaaa fathima peru mattuuuuu',
 'aaaa fathima peru mattuuuuu ath',
 'aaaa fathima peru mattuuuuu ath njangale',
 'aaaa item',
 'aaaa item powlichu',
 'aaaa item powlichu ntae',
 'aaaa item powlichu ntae ponno',
 'aaaa item powlichu ntae ponno namichu',
 'aaaa road',
 'aaaa road onnu',
 'aaaa road onnu nannakkan',
 'aaaa road onnu nannakkan parayanam',
 'aaaa road onnu nannakkan parayanam cherpulashery',
 'aaaaa',
 'aaaaa endu',
 'aaaaa endu pathudu',
 'aaaaa endu pathudu irupenka',
 'aaaaaa',
 'aaaaaa nadakkk',
 'aaaaaa nadakkk ippo',
 'aaaaaa nadakkk ippo thannee',
 'aaaaaa nadakkk ippo thannee pokaaa',
 'aaaahhh',
 'aaaahhh rendumeeee',
 'aaaahhh rendumeeee venum',
 'aaaahhh rendumeeee venum ayyyyyyooo',
 'aaaahhh rendumeeee venum ayyyyyyooo ammalayum',
 'aaaahhh rendumeeee venum ayyyyyyooo ammalayum ponnayum',
 'aaaal',
 'aaaal allengilum',
 'aaaal allengilum nammal',
 'aaaal allengilum nammal sadharana',
 'aaaal allengilum nammal sadharana janaghal',
 'aaaal allengilum nammal sadharana janaghal ariyunna',
 'aaaalaaavunnavvan',
 'aaaan',
 'aaaan mole',
 'aaaan mole ozhivaaak',
 'aaaan mole ozhivaaak ivale',
 'aaaan mole ozhivaaak ivale okke',
 'aaaan mole ozhivaaak ivale okke thall',
 'aaaanu',
 'aaaanu kavala',
 'aaaanu kavala prasangam',
 'aaaanu kavala prasangam nadathunnathu',
 'aaadharsam',
 'aaadharsam parayumbozhum',
 'aaadharsam parayumbozhum pala',
 'aaadharsam parayumbozhum pala chettatharavum',
 'aaadharsam parayumbozhum pala chettatharavum kanikkunnu',
 'aaah',
 'aaah dusky',
 'aaah dusky mundi',
 'aaah dusky mundi serialye',
 'aaah dusky mundi serialye ipdi',
 'aaah dusky mundi serialye ipdi clevage',
 'aaahh',
 'aaahh antha',
 'aaahh antha kutty',
 'aaahh antha kutty jacket',
 'aaahh antha kutty jacket oda',
 'aaahh antha kutty jacket oda potruka',
 'aaahn',
 'aaahn nik',
 'aaahn nik ariyaan',
 'aaahn nik ariyaan padilanjit',
 'aaahn nik ariyaan padilanjit chooikaan',
 'aaahn nik ariyaan padilanjit chooikaan url',
 'aaakkki',
 'aaakkki kanum',
 'aaakkki kanum url',
 'aaakkki kanum url parayanoo',
 'aaalkaare',
 'aaalkaare kaanikkenda',
 'aaalu',
 'aaalu pundaiyaave',
 'aaalu pundaiyaave mathikalana',
 'aaalu pundaiyaave mathikalana pinna',
 'aaalu pundaiyaave mathikalana pinna yethukuda',
 'aaalu pundaiyaave mathikalana pinna yethukuda avanuku',
 'aaalukal',
 'aaalukal paryum',
 'aaana',
 'aaana padathula',
 'aaana padathula full',
 'aaana padathula full ah',
 'aaana padathula full ah ilukurathuku',
 'aaana padathula full ah ilukurathuku ready',
 'aaanallo',
 'aaanallo edo',
 'aaanallo edo bro',
 'aaanallo edo bro melle',
 'aaanallo edo bro melle vittrudooo',
 'aaanallo edo bro melle vittrudooo pu',
 'aaanenkil',
 'aaanenkil url',
 'aaanenkil url enthnaaaddiii',
 'aaanenkil url enthnaaaddiii aaa',
 'aaanenkil url enthnaaaddiii aaa paavam',
 'aaanenkil url enthnaaaddiii aaa paavam devathaye',
 'aaanenn',
 'aaanenn matro',
 'aaanenn matro enikariya',
 'aaanennu',
 'aaanennu thonnunnu',
 'aaano',
 'aaano arinjilla',
 'aaano arinjilla pavam',
 'aaano arinjilla pavam femichees',
 'aaano myre',
 'aaano myre nee',
 'aaano myre nee araadee',
 'aaano myre nee araadee pulle',
 'aaano myre nee araadee pulle nayinte',
 'aaanu',
 'aaanu aa',
 'aaanu aa panna',
 'aaanu aa panna enit',
 'aaanu aa panna enit ipo',
 'aaanu aa panna enit ipo nallavane',
 'aaanu baacki',
 'aaanu konathile',
 'aaanu konathile oru',
 'aaanu konathile oru charcha',
 'aaanu nattile',
 'aaanu nattile ivarude',
 'aaanu nattile ivarude avastha',

In [163]:
char_tfidf.get_feature_names()

[' ',
 ' a',
 ' a ',
 ' a c',
 ' a ch',
 ' a cha',
 ' a chal',
 ' a chali',
 ' a e',
 ' a en',
 ' a enn',
 ' a enn ',
 ' a enn p',
 ' a g',
 ' a go',
 ' a goo',
 ' a good',
 ' a good ',
 ' a n',
 ' a ne',
 ' a neg',
 ' a nega',
 ' a negat',
 ' a o',
 ' a ot',
 ' a oth',
 ' a otha',
 ' a othaa',
 ' a t',
 ' a th',
 ' a thr',
 ' a thre',
 ' a threa',
 ' aa',
 ' aa ',
 ' aa a',
 ' aa aa',
 ' aa aal',
 ' aa aala',
 ' aa ac',
 ' aa acc',
 ' aa acco',
 ' aa ad',
 ' aa adi',
 ' aa adik',
 ' aa adis',
 ' aa at',
 ' aa ath',
 ' aa athe',
 ' aa b',
 ' aa ba',
 ' aa baa',
 ' aa baal',
 ' aa be',
 ' aa bed',
 ' aa bedi',
 ' aa c',
 ' aa ca',
 ' aa cas',
 ' aa casa',
 ' aa ci',
 ' aa cin',
 ' aa cine',
 ' aa d',
 ' aa da',
 ' aa da ',
 ' aa da n',
 ' aa da u',
 ' aa dh',
 ' aa dha',
 ' aa dhan',
 ' aa du',
 ' aa dup',
 ' aa dupl',
 ' aa f',
 ' aa fi',
 ' aa fil',
 ' aa film',
 ' aa g',
 ' aa ga',
 ' aa gat',
 ' aa gath',
 ' aa gay',
 ' aa gaya',
 ' aa i',
 ' aa ir',
 ' aa iru',
 ' aa iruk',
 ' aa is',
 ' aa ish',
 ' aa isht',
 ' aa it',
 ' aa ith',
 ' aa ithu',
 ' aa k',
 ' aa ka',
 ' aa kaa',
 ' aa kaat',
 ' aa kal',
 ' aa kala',
 ' aa kan',
 ' aa kann',
 ' aa kar',
 ' aa karu',
 ' aa kas',
 ' aa kasi',
 ' aa ko',
 ' aa koc',
 ' aa koch',
 ' aa ku',
 ' aa ku ',
 ' aa ku r',
 ' aa kun',
 ' aa kunj',
 ' aa kup',
 ' aa kupp',
 ' aa kut',
 ' aa kutt',
 ' aa m',
 ' aa ma',
 ' aa mat',
 ' aa math',
 ' aa mi',
 ' aa mic',
 ' aa mic ',
 ' aa mo',
 ' aa mon',
 ' aa mon ',
 ' aa mov',
 ' aa movi',
 ' aa mu',
 ' aa mug',
 ' aa muga',
 ' aa n',
 ' aa na',
 ' aa naa',
 ' aa naar',
 ' aa nan',
 ' aa nan ',
 ' aa nar',
 ' aa nari',
 ' aa o',
 ' aa od',
 ' aa odu',
 ' aa oduk',
 ' aa of',
 ' aa off',
 ' aa offi',
 ' aa or',
 ' aa oru',
 ' aa oru ',
 ' aa p',
 ' aa pa',
 ' aa paa',
 ' aa paat',
 ' aa pan',
 ' aa pand',
 ' aa pann',
 ' aa par',
 ' aa para',
 ' aa pat',
 ' aa patt',
 ' aa pav',
 ' aa pava',
 ' aa pay',
 ' aa payy',
 ' aa pe',
 ' aa pee',
 ' aa peed',
 ' aa pen',
 ' aa penk',
 ' aa per',
 ' aa peri',
 ' aa peru',
 ' aa pes',
 ' aa pesa',
 ' aa po',
 ' aa poo',
 ' aa poor',
 ' aa pos',
 ' aa posi',
 ' aa r',
 ' aa re',
 ' aa res',
 ' aa resp',
 ' aa s',
 ' aa sa',
 ' aa sam',
 ' aa sama',
 ' aa sams',
 ' aa st',
 ' aa sth',
 ' aa sthr',
 ' aa su',
 ' aa sup',
 ' aa supp',
 ' aa t',
 ' aa ta',
 ' aa tan',
 ' aa tane',
 ' aa th',
 ' aa tha',
 ' aa thaa',
 ' aa that',
 ' aa thi',
 ' aa thir',
 ' aa to',
 ' aa tor',
 ' aa tort',
 ' aa v',
 ' aa va',
 ' aa vaa',
 ' aa vaak',
 ' aa vam',
 ' aa vams',
 ' aa vd',
 ' aa vdo',
 ' aa vdo ',
 ' aa ve',
 ' aa ver',
 ' aa veru',
 ' aa vi',
 ' aa vid',
 ' aa vide',
 ' aa vr',
 ' aa vri',
 ' aa vrit',
 ' aaa',
 ' aaa ',
 ' aaa a',
 ' aaa aa',
 ' aaa aaa',
 ' aaa ar',
 ' aaa art',
 ' aaa c',
 ' aaa co',
 ' aaa cor',
 ' aaa k',
 ' aaa ke',
 ' aaa ked',
 ' aaa ker',
 ' aaa kn',
 ' aaa kna',
 ' aaa ku',
 ' aaa kun',
 ' aaa m',
 ' aaa ma',
 ' aaa mam',
 ' aaa my',
 ' aaa myr',
 ' aaa myt',
 ' aaa n',
 ' aaa na',
 ' aaa naa',
 ' aaa nay',
 ' aaa p',
 ' aaa pa',
 ' aaa paa',
 ' aaa pe',
 ' aaa per',
 ' aaa po',
 ' aaa pol',
 ' aaa pr',
 ' aaa pre',
 ' aaa r',
 ' aaa re',
 ' aaa rev',
 ' aaa s',
 ' aaa sa',
 ' aaa sam',
 ' aaa so',
 ' aaa sou',
 ' aaa st',
 ' aaa sth',
 ' aaa t',
 ' aaa th',
 ' aaa the',
 ' aaaa',
 ' aaaa ',
 ' aaaa e',
 ' aaaa ev',
 ' aaaa f',
 ' aaaa fa',
 ' aaaa r',
 ' aaaa ro',
 ' aaaaa',
 ' aaaaa ',
 ' aaaaa e',
 ' aaaal',
 ' aaaal ',
 ' aaaal a',
 ' aaaala',
 ' aaaalaa',
 ' aaaan',
 ' aaaan ',
 ' aaaan m',
 ' aaaanu',
 ' aaaanu ',
 ' aaad',
 ' aaadh',
 ' aaadha',
 ' aaadhar',
 ' aaah',
 ' aaah ',
 ' aaah d',
 ' aaah du',
 ' aaahh',
 ' aaahh ',
 ' aaahh a',
 ' aaahn',
 ' aaahn ',
 ' aaahn n',
 ' aaak',
 ' aaakk',
 ' aaakkk',
 ' aaakkki',
 ' aaal',
 ' aaalk',
 ' aaalka',
 ' aaalkaa',
 ' aaalu',
 ' aaaluk',
 ' aaaluka',
 ' aaan',
 ' aaana',
 ' aaanal',
 ' aaanall',
 ' aaane',
 ' aaanen',
 ' aaanenk',
 ' aaanenn',
 ' aaano',
 ' aaano ',
 ' aaano m',
 ' aaanu',
 ' aaanu ',
 ' aaanu a',
 ' aaanu b',
 ' aaanu e',
 ' aaanu k',
 ' aaanu p',
 ' aaanug',
 ' aaanuga',
 ' aaanun',
 ' aaanung',
 ' aaanuu',
 ' aaanuu ',
 ' aaar',
 ' aaara',
 ' aaara ',
 ' aaara r',
 ' aaat',
 ' aaath',
 ' aaatha',
 ' aaatha ',
 ' aaay',
 ' aaayi',
 ' aaayi ',
 ' aaayi k',
 ' aaayo',
 ' aaayol',
 ' aaayolc',
 ' aab',
 ' aaba',
 ' aabal',
 ' aabala',
 ' aabala ',
 ' aabas',
 ' aabasa',
 ' aabasam',
 ' aac',
 ' aach',
 ' aacha',
 ' aachar',
 ' aachara',
 ' aachary',
 ' aache',
 ' aache ',
 ' aache e',
 ' aachi',
 ' aachi ',
 ' aachi p',
 ' aachu',
 ' aachu ',
 ' aachu a',
 ' aachu d',
 ' aachu e',
 ' aachu h',
 ' aachu i',
 ' aachu l',
 ' aachu m',
 ' aachu n',
 ' aachu p',
 ' aachu s',
 ' aachu t',
 ' aachu u',
 ' aachum',
 ' aachum ',
 ' aachun',
 ' aachune',
 ' aad',
 ' aad ',
 ' aad j',
 ' aad ja',
 ' aad jal',
 ' aada',
 ' aada ',
 ' aada p',
 ' aada pa',
 ' aadam',
 ' aadam ',
 ' aadam p',
 ' aadh',
 ' aadhi',
 ' aadhi ',
 ' aadhi n',
 ' aadhu',
 ' aadhur',
 ' aadhura',
 ' aadhy',
 ' aadhya',
 ' aadhyam',
 ' aadi',
 ' aadi ',
 ' aadi a',
 ' aadi aa',
 ' aadi n',
 ' aadi no',
 ' aadi u',
 ' aadi ul',
 ' aadic',
 ' aadich',
 ' aadichi',
 ' aadii',
 ' aadiii',
 ' aadiii ',
 ' aadik',
 ' aadika',
 ' aadikan',
 ' aadin',
 ' aadine',
 ' aadine ',
 ' aadit',
 ' aaditu',
 ' aaditu ',
 ' aadu',
 ' aadu ',
 ' aadu n',
 ' aadu na',
 ' aadun',
 ' aaduna',
 ' aaduna ',
 ' aaduni',
 ' aadunik',
 ' aadur',
 ' aadura',
 ' aadurar',
 ' aady',
 ' aadya',
 ' aadya ',
 ' aadya m',
 ' aadyam',
 ' aadyam ',
 ' aadyama',
 ' aae',
 ' aae ',
 ' aae i',
 ' aae ir',
 ' aae iru',
 ' aae s',
 ' aae so',
 ' aae sol',
 ' aag',
 ' aaga',
 ' aaga ',
 ' aaga i',
 ' aaga ir',
 ' aaga k',
 ' aaga ke',
 ' aaga ko',
 ' aaga m',
 ' aaga ma',
 ' aaga mo',
 ' aaga p',
 ' aaga po',
 ' aagaa',
 ' aagaat',
 ' aagaath',
 ' aagad',
 ' aagadh',
 ' aagadhu',
 ' aagal',
 ' aagala',
 ' aagala ',
 ' aagalan',
 ' aagam',
 ' aagam ',
 ' aagam i',
 ' aagan',
 ' aagan ',
 ' aagan o',
 ' aaganu',
 ' aaganum',
 ' aagat',
 ' aagath',
 ' aagatha',
 ' aagathu',
 ' aagav',
 ' aagave',
 ' aagave ',
 ' aagi',
 ' aagi ',
 ' aagi a',
 ' aagi ap',
 ' aagi e',
 ' aagi el',
 ' aagi j',
 ' aagi ju',
 ' aagi l',
 ' aagi la',
 ' aagi m',
 ' aagi mu',
 ' aagi r',
 ' aagi ro',
 ' aagi v',
 ' aagi va',
 ' aagid',
 ' aagidu',
 ' aagiduc',
 ' aagidum',
 ' aagik',
 ' aagiki',
 ' aagikir',
 ' aagir',
 ' aagirn',
 ' aagirnt',
 ' aagiru',
 ' aagiruk',
 ' aagit',
 ' aagita',
 ' aagita ',
 ' aagitan',
 ' aagiti',
 ' aagitii',
 ' aagito',
 ' aagitom',
 ' aagitu',
 ' aagitu ',
 ' aagiu',
 ' aagium',
 ' aagium ',
 ' aagr',
 ' aagra',
 ' aagrah',
 ' aagraha',
 ' aagrahi',
 ' aagu',
 ' aagud',
 ' aagudh',
 ' aagudhu',
 ' aagum',
 ' aagum ',
 ' aagum a',
 ' aagum b',
 ' aagum i',
 ' aagum k',
 ' aagum p',
 ' aagum y',
 ' aaguma',
 ' aaguma ',
 ' aagume',
 ' aagume ',
 ' aagumo',
 ' aagumo ',
 ' aagur',
 ' aagura',
 ' aagura ',
 ' aagurad',
 ' aagut',
 ' aaguth',
 ' aagutha',
 ' aaguthu',
 ' aah',
 ' aah ',
 ' aah k',
 ' aah ku',
 ' aah kun',
 ' aah l',
 ' aah li',
 ' aah lin',
 ' aah m',
 ' aah ma',
 ' aah mak',
 ' aah n',
 ' aah na',
 ' aah nad',
 ' aah p',
 ' aah pr',
 ' aah pre',
 ' aahd',
 ' aahda',
 ' aahda ',
 ' aahda e',
 ' aahh',
 ' aahh ',
 ' aahh c',
 ' aahh ch',
 ' aahhh',
 ' aahhh ',
 ' aahhh u',
 ' aahhhh',
 ' aahhhh ',
 ' aahi',
 ' aahit',
 ' aahitt',
 ' aahitti',
 ' aahn',
 ' aahn ',
 ' aahn a',
 ' aahn at',
 ' aahn k',
 ' aahn ka',
 ' aahn p',
 ' aahn pr',
 ' aahnu',
 ' aahnu ',
 ' aahnu c',
 ' aai',
 ' aai ',
 ' aai p',
 ' aai pa',
 ' aai pat',
 ' aaid',
 ' aaida',
 ' aaidan',
 ' aaidanu',
 ' aail',
 ' aaill',
 ' aaille',
 ' aaille ',
 ' aair',
 ' aairn',
 ' aairnu',
 ' aairnu ',
 ' aairu',
 ' aairuc',
 ' aairuch',
 ' aairuk',
 ' aairuku',
 ' aait',
 ' aait ',
 ' aait v',
 ' aait vr',
 ' aaita',
 ' aaita ',
 ' aaita v',
 ' aaite',
 ' aaiten',
 ' aaiten ',
 ' aaitn',
 ' aaitu',
 ' aaitu ',
 ' aaitu b',
 ' aaituv',
 ' aaituva',
 ' aaity',
 ' aaitya',
 ' aaitya ',
 ' aak',
 ' aaka',
 ' aaka ',
 ' aaka m',
 ' aaka ma',
 ' aakaa',
 ' aakaan',
 ' aakaana',
 ' aakad',
 ' aakadi',
 ' aakadi ',
 ' aakal',
 ' aakall',
 ' aakallo',
 ' aakan',
 ' aakan ',
 ' aakan a',
 ' aakan n',
 ' aakan p',
 ' aakan v',
 ' aakat',
 ' aakath',
 ' aakathi',
 ' aaki',
 ' aaki ',
 ' aaki a',
 ' aaki at',
 ' aaki i',
 ' aaki ip',
 ' aaki v',
 ' aaki vi',
 ' aakid',
 ' aakidu',
 ' aakiduc',
 ' aakir',
 ' aakiri',
 ' aakirin',
 ' aakit',
 ' aakite',
 ' aakiten',
 ' aakiy',
 ' aakiya',
 ' aakiyaa',
 ' aakiyal',
 ' aakiyi',
 ' aakiyir',
 ' aakk',
 ' aakka',
 ' aakkan',
 ' aakkana',
 ' aakki',
 ' aakki ',
 ' aakki v',
 ' aakkiv',
 ' aakkive',
 ' aakkiy',
 ' aakkiya',
 ' aakkiyi',
 ' aakku',
 ' aakkun',
 ' aakkunn',
 ' aakm',
 ' aakr',
 ' aakra',
 ' aakram',
 ' aakrama',
 ' aakrami',
 ' aakran',
 ' aakrang',
 ' aakt',
 ' aaktt',
 ' aaktte',
 ' aaktte ',
 ' aaku',
 ' aakum',
 ' aakum ',
 ' aakum k',
 ' aakum m',
 ' aakum o',
 ' aakuma',
 ' aakumal',
 ' aakun',
 ' aakuna',
 ' aakunat',
 ' aakunn',
 ' aakunna',
 ' aal',
 ' aal ',
 ' aal a',
 ' aal ah',
 ' aal ah ',
 ' aal an',
 ' aal ann',
 ' aal anu',
 ' aal n',
 ' aal na',
 ' aal nat',
 ' aal ni',
 ' aal nin',
 ' aal p',
 ' aal pa',
 ' aal paa',
 ' aal v',
 ' aal ve',
 ' aal ven',
 ' aala',
 ' aala ',
 ' aala k',
 ' aala ka',
 ' aala n',
 ' aala na',
 ' aala ne',
 ' aala p',
 ' aala p ',
 ' aala pa',
 ' aala t',
 ' aala th',
 ' aala v',
 ' aala va',
 ' aalaa',
 ' aalaa ',
 ' aalaa e',
 ' aalaa m',
 ' aalaan',
 ' aalaanu',
 ' aalak',
 ' aalaka',
 ' aalaka ',
 ' aalam',
 ' aalame',
 ' aalamee',
 ' aalan',
 ' aalan ',
 ' aalan a',
 ' aalann',
 ' aalanno',
 ' aalano',
 ' aalanu',
 ' aalanu ',
 ' aalay',
 ' aalaye',
 ' aalaye ',
 ' aalayi',
 ' aalayil',
 ' aald',
 ' aalde',
 ' aalde ',
 ' aalde f',
 ' aale',
 ' aale ',
 ' aale m',
 ' aale ma',
 ' aali',
 ' aalil',
 ' aalill',
 ' aalille',
 ' aalk',
 ' aalka',
 ' aalkaa',
 ' aalkaar',
 ' aalkar',
 ' aalkar ',
 ' aalkk',
 ' aalkka',
 ' aalkkar',
 ' aalko',
 ' aalkoo',
 ' aalkoot',
 ' aalku',
 ' aalkul',
 ' aalkulu',
 ' aall',
 ' aalle',
 ' aalle ',
 ' aalle k',
 ' aalle r',
 ' aaln',
 ' aalnu',
 ' aalnu ',
 ' aalnu k',
 ' aalo',
 ' aaloc',
 ' aaloch',
 ' aalochi',
 ' aalog',
 ' aalogi',
 ' aalogik',
 ' aaloj',
 ' aaloji',
 ' aalojik',
 ' aalon',
 ' aalonn',
 ' aalonnu',
 ' aalu',
 ' aalu ',
 ' aalu a',
 ' aalu aa',
 ' aalu b',
 ' aalu bu',
 ' aalu n',
 ' aalu nu',
 ' aalu p',
 ' aalu po',
 ' aalu pu',
 ' aalu t',
 ' aalu th',
 ' aalu u',
 ' aalu un',
 ' aaluk',
 ' aaluka',
 ' aalukal',
 ' aaluku',
 ' aaluku ',
 ' aalum',
 ' aalum ',
 ' aalum k',
 ' aalun',
 ' aalung',
 ' aalunga',
 ' aalunu',
 ' aalunu ',
 ' aam',
 ' aam ',
 ' aam n',
 ' aam no',
 ' aam noo',
 ' aam p',
 ' aam pa',
 ' aam par',
 ' aam pp',
 ' aam ppl',
 ' aam t',
 ' aam th',
 ' aam tha',
 ' aam thi',
 ' aama',
 ' aama ',
 ' aama b',
 ' aama bo',
 ' aama d',
 ' aama du',
 ' aama n',
 ' aama na',
 ' aama p',
 ' aama pu',
 ' aama v',
 ' aama vj',
 ' aamab',
 ' aamaba',
 ' aamabal',
 ' aamai',
 ' aamai ',
 ' aamai c',
 ' aamai g',
 ' aamai k',
 ' aamai n',
 ' aamai p',
 ' aamaig',
 ' aamaiga',
 ' aamain',
 ' aamaing',
 ' aamais',
 ' aamais ',
 ' aamaiy',
 ' aamaiya',
 ' aamas',
 ' aamasa',
 ' aamasam',
 ' aamb',
 ' aamba',
 ' aambal',
 ' aambala',
 ' aambi',
 ' aambil',
 ' aambila',
 ' aame',
 ' aamee',
 ' aameen',
 ' aameen ',
 ' aan',
 ' aan ',
 ' aan a',
 ' aan ap',
 ' aan app',
 ' aan at',
 ' aan ath',
 ' aan av',
 ' aan ava',
 ' aan ay',
 ' aan aya',
 ' aan b',
 ' aan be',
 ' aan bes',
 ' aan br',
 ' aan bro',
 ' aan c',
 ' aan ch',
 ' aan che',
 ' aan co',
 ' aan com',
 ' aan e',
 ' aan el',
 ' aan ell',
 ' aan en',
 ' aan eni',
 ' aan h',
 ' aan he',
 ' aan hel',
 ' aan i',
 ' aan in',
 ' aan ing',
 ' aan is',
 ' aan isl',
 ' aan l',
 ' aan li',
 ' aan lik',
 ' aan m',
 ' aan ma',
 ' aan mai',
 ' aan mo',
 ' aan mob',
 ' aan n',
 ' aan na',
 ' aan nam',
 ' aan ne',
 ' aan ne ',
 ' aan nee',
 ' aan o',
 ' aan or',
 ' aan oru',
 ' aan p',
 ' aan pa',
 ...]

In [164]:
len(tfidf.vocabulary_), len(char_tfidf.vocabulary_), len(tfidf.get_feature_names()), len(char_tfidf.get_feature_names())

(282975, 862753, 282975, 862753)

In [165]:
X, X_char

(<5600x282975 sparse matrix of type '<class 'numpy.float64'>'
 	with 356362 stored elements in Compressed Sparse Row format>,
 <5600x862753 sparse matrix of type '<class 'numpy.float64'>'
 	with 3222473 stored elements in Compressed Sparse Row format>)

In [166]:
from scipy.sparse import hstack
train=hstack([X,X_char])
train

<5600x1145728 sparse matrix of type '<class 'numpy.float64'>'
	with 3578835 stored elements in COOrdinate format>

In [167]:
Xt=tfidf.transform(X_test) 
Xt_char=char_tfidf.transform(X_test)

In [168]:
Xt, Xt_char

(<2401x282975 sparse matrix of type '<class 'numpy.float64'>'
 	with 42366 stored elements in Compressed Sparse Row format>,
 <2401x862753 sparse matrix of type '<class 'numpy.float64'>'
 	with 1119428 stored elements in Compressed Sparse Row format>)

In [169]:
traintest=hstack([Xt,Xt_char])
traintest

<2401x1145728 sparse matrix of type '<class 'numpy.float64'>'
	with 1161794 stored elements in COOrdinate format>

In [170]:
mal_hasoc=pd.read_excel("Tamil+Malya.xlsx", header=None)
mal_hasoc=mal_hasoc.rename(columns={0:'ID', 1:'Tweets'})
test_Mal_Hasoc=mal_hasoc['Tweets']

test_Mal_Hasoc_word=tfidf.transform(test_Mal_Hasoc)
test_Mal_Hasoc_char=char_tfidf.transform(test_Mal_Hasoc)
test_Mal_Hasoc_word_char=hstack([test_Mal_Hasoc_word,test_Mal_Hasoc_char])

In [171]:
test_Mal_Hasoc_word, test_Mal_Hasoc_char, test_Mal_Hasoc_word_char

(<1940x282975 sparse matrix of type '<class 'numpy.float64'>'
 	with 18823 stored elements in Compressed Sparse Row format>,
 <1940x862753 sparse matrix of type '<class 'numpy.float64'>'
 	with 837874 stored elements in Compressed Sparse Row format>,
 <1940x1145728 sparse matrix of type '<class 'numpy.float64'>'
 	with 856697 stored elements in COOrdinate format>)

In [172]:
test_Mal_Hasoc_word, test_Mal_Hasoc_char, test_Mal_Hasoc_word_char

(<1940x282975 sparse matrix of type '<class 'numpy.float64'>'
 	with 18823 stored elements in Compressed Sparse Row format>,
 <1940x862753 sparse matrix of type '<class 'numpy.float64'>'
 	with 837874 stored elements in Compressed Sparse Row format>,
 <1940x1145728 sparse matrix of type '<class 'numpy.float64'>'
 	with 856697 stored elements in COOrdinate format>)

In [173]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

In [174]:
def trainer(model_obj, param, X, X_char, train, traintest, Y, y_test):
    
    GSCV=GridSearchCV(model_obj, param , cv=5,return_train_score=False)
    GSCV.fit(X,Y)
    #Training Classifier with TF-IDF Features Word n-gram
    #model_obj.fit(X,Y)
    print("Accuracy of Word n-gram(1,6) :", (GSCV.score(tfidf.transform(X_test), y_test)))
    #Printing Classification Report
    predict=GSCV.predict(Xt)
    print(classification_report(y_test, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word=GSCV.predict(test_Mal_Hasoc_word)


  #Training Classifier with TF-IDF Features Char n-gram
    GSCV.fit(X_char, Y)
    print("Accuracy of Char n-gram(1,8) :", (GSCV.score(char_tfidf.transform(X_test), y_test)))
    predict=GSCV.predict(Xt_char)
    print(classification_report(y_test, predict))
   #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    char=GSCV.predict(test_Mal_Hasoc_char)

        
              
    #Training Classifier with TF-IDF Features Combine Word n-gram & Char n-gram
    GSCV.fit(train, Y)
    print("Accuracy of Combinining word & Char n-gram", (GSCV.score(traintest, y_test)))
    #Printing Classification Report
    predict=GSCV.predict(traintest)
    print(classification_report(y_test, predict))
    #Printing Confusion Matrix
    conf_mat=confusion_matrix(y_test, predict)
    print("Best Parameters ", GSCV.best_params_)
    print("Best Score ", GSCV.best_score_)
    print(" ")
    print("Confusion Matrix")
    print(conf_mat)
    print(" ")
    word_char=GSCV.predict(test_Mal_Hasoc_word_char)
    
    return word, char, word_char

# Implementing SVC

In [175]:
from sklearn.svm import SVC
svc=SVC()
print("SVC")
param={'kernel':('linear', 'rbf'), 'gamma':('auto', 'scale'), 'C':[0.9, 10, 20, 30]}
w_svc,c_svc,wc_svc=trainer(svc,param, X, X_char, train, traintest, Y, y_test)

SVC
Accuracy of Word n-gram(1,6) : 0.7671803415243649
              precision    recall  f1-score   support

           0       0.74      0.81      0.78      1191
           1       0.80      0.72      0.76      1210

    accuracy                           0.77      2401
   macro avg       0.77      0.77      0.77      2401
weighted avg       0.77      0.77      0.77      2401

Best Parameters  {'C': 30, 'gamma': 'auto', 'kernel': 'linear'}
Best Score  0.7633928571428571

Confusion Matrix
[[965 226]
 [333 877]]

Accuracy of Char n-gram(1,8) : 0.7859225322782174
              precision    recall  f1-score   support

           0       0.77      0.81      0.79      1191
           1       0.80      0.77      0.78      1210

    accuracy                           0.79      2401
   macro avg       0.79      0.79      0.79      2401
weighted avg       0.79      0.79      0.79      2401

Best Parameters  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
Best Score  0.7930357142857143

Confusion Matrix
[[959 232]
 [282 928]]

Accuracy of Combinining word & Char n-gram 0.8017492711370262
              precision    recall  f1-score   support

           0       0.79      0.82      0.80      1191
           1       0.81      0.79      0.80      1210

    accuracy                           0.80      2401
   macro avg       0.80      0.80      0.80      2401
weighted avg       0.80      0.80      0.80      2401

Best Parameters  {'C': 0.9, 'gamma': 'auto', 'kernel': 'linear'}
Best Score  0.7973214285714286

Confusion Matrix
[[972 219]
 [257 953]]

In [178]:
wc_svc=pd.DataFrame(wc_svc, columns=["Combine Word Char_SVC"])
mal_tam=pd.concat([mal_hasoc, wc_svc['Combine Word Char_SVC']], axis=1)
mal_tam['Combine Word Char_SVC'] = mal_tam['Combine Word Char_SVC'].map({0 : 'NOT', 1 : 'OFF'})

mal_tam.to_csv("Mal_Tamil_SVC_Results.xlsx")

In [179]:
mal_tam

,ID,Tweets,Combine Word Char_SVC
0,MA_YT5000,Chenkol vendath thanne aayirunnu....,NOT
1,MA_YT5001,Sundardasinte bhakshnam vakkukal ano?,NOT
2,MA_YT5002,Akasha dooth oru copy adi movie anu 'Who will ...,NOT
3,MA_YT5003,Purath onnum pondade... oru pennum payyanum on...,NOT
4,MA_YT5004,Avasanam Fahad oru Oscar medikkumbazhum lalett...,OFF
...,...,...,...
1935,TA_TW9701,RT : Engineering Mudichu 2 years ayuruchu Adh...,NOT
1936,TA_TW9702,To #TAG oruthanvagaloda saavula kooda controv...,NOT
1937,TA_TW9703,Veetla matna.. Reason illama 6year love Thooki...,OFF
1938,TA_TW9704,"Neenga enkitta pesalam vena ""indu madham enge...",NOT
1939,TA_TW9705,"Kantha sasti kavasatha, neenga konjam thamizh...",NOT

# Implementing Multinomial Naive Bayes

In [176]:
from sklearn.naive_bayes import MultinomialNB
MNB=MultinomialNB(alpha=2.0)
param={'alpha':[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,2.0]}
print("Multi Nominal Bayes")
w_mnb,c_mnb,wc_mnb=trainer(MNB,param, X, X_char, train, traintest, Y, y_test)

Multi Nominal Bayes
Accuracy of Word n-gram(1,6) : 0.7650978758850479
              precision    recall  f1-score   support

           0       0.73      0.84      0.78      1191
           1       0.81      0.69      0.75      1210

    accuracy                           0.77      2401
   macro avg       0.77      0.77      0.76      2401
weighted avg       0.77      0.77      0.76      2401

Best Parameters  {'alpha': 0.5}
Best Score  0.76375

Confusion Matrix
[[1001  190]
 [ 374  836]]

Accuracy of Char n-gram(1,8) : 0.7788421491045397
              precision    recall  f1-score   support

           0       0.74      0.85      0.79      1191
           1       0.83      0.71      0.76      1210

    accuracy                           0.78      2401
   macro avg       0.78      0.78      0.78      2401
weighted avg       0.78      0.78      0.78      2401

Best Parameters  {'alpha': 0.5}
Best Score  0.7951785714285714

Confusion Matrix
[[1012  179]
 [ 352  858]]

Accuracy of Combinining word & Char n-gram 0.7913369429404414
              precision    recall  f1-score   support

           0       0.75      0.86      0.80      1191
           1       0.84      0.72      0.78      1210

    accuracy                           0.79      2401
   macro avg       0.80      0.79      0.79      2401
weighted avg       0.80      0.79      0.79      2401

Best Parameters  {'alpha': 0.5}
Best Score  0.7975

Confusion Matrix
[[1026  165]
 [ 336  874]]

In [119]:
wc_mnb=pd.DataFrame(wc_mnb, columns=["Combine Word Char_MNB"])
mal_tam=pd.concat([mal_hasoc, wc_mnb['Combine Word Char_MNB']], axis=1)
mal_tam['Combine Word Char_MNB'] = mal_tam['Combine Word Char_MNB'].map({0 : 'NOT', 1 : 'OFF'})

mal_tam.to_csv("Mal_Tamil_MNB_Results.xlsx")

In [120]:
mal_tam

,ID,Tweets,Combine Word Char_MNB
0,MA_YT5000,Chenkol vendath thanne aayirunnu....,NOT
1,MA_YT5001,Sundardasinte bhakshnam vakkukal ano?,NOT
2,MA_YT5002,Akasha dooth oru copy adi movie anu 'Who will ...,NOT
3,MA_YT5003,Purath onnum pondade... oru pennum payyanum on...,NOT
4,MA_YT5004,Avasanam Fahad oru Oscar medikkumbazhum lalett...,NOT
...,...,...,...
1935,TA_TW9701,RT : Engineering Mudichu 2 years ayuruchu Adh...,NOT
1936,TA_TW9702,To #TAG oruthanvagaloda saavula kooda controv...,NOT
1937,TA_TW9703,Veetla matna.. Reason illama 6year love Thooki...,OFF
1938,TA_TW9704,"Neenga enkitta pesalam vena ""indu madham enge...",NOT
1939,TA_TW9705,"Kantha sasti kavasatha, neenga konjam thamizh...",NOT

# Implementing Logistic Regression

In [180]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(random_state=40, solver='lbfgs')
param={'solver':('newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'), 'multi_class':('ovr', 'auto')}
print("Logisitc Regression")
w_lr,c_lr,wc_lr=trainer(LR,param, X, X_char, train, traintest, Y, y_test)

Logisitc Regression
Accuracy of Word n-gram(1,6) : 0.7642648896293212
              precision    recall  f1-score   support

           0       0.72      0.85      0.78      1191
           1       0.82      0.68      0.74      1210

    accuracy                           0.76      2401
   macro avg       0.77      0.76      0.76      2401
weighted avg       0.77      0.76      0.76      2401

Best Parameters  {'multi_class': 'ovr', 'solver': 'saga'}
Best Score  0.7364285714285714

Confusion Matrix
[[1015  176]
 [ 390  820]]

Accuracy of Char n-gram(1,8) : 0.7805081216159934
              precision    recall  f1-score   support

           0       0.76      0.82      0.79      1191
           1       0.81      0.74      0.77      1210

    accuracy                           0.78      2401
   macro avg       0.78      0.78      0.78      2401
weighted avg       0.78      0.78      0.78      2401

Best Parameters  {'multi_class': 'ovr', 'solver': 'newton-cg'}
Best Score  0.7846428571428572

Confusion Matrix
[[976 215]
 [312 898]]

Accuracy of Combinining word & Char n-gram 0.787588504789671
              precision    recall  f1-score   support

           0       0.76      0.83      0.79      1191
           1       0.82      0.75      0.78      1210

    accuracy                           0.79      2401
   macro avg       0.79      0.79      0.79      2401
weighted avg       0.79      0.79      0.79      2401

Best Parameters  {'multi_class': 'ovr', 'solver': 'liblinear'}
Best Score  0.7892857142857143

Confusion Matrix
[[987 204]
 [306 904]]

# Implementing Random Forest Classifier

In [121]:
from sklearn.ensemble import RandomForestClassifier
RFC=RandomForestClassifier(n_estimators=13)
param={'n_estimators':[10, 20, 30]}
print("Random Forest Classifier")
w_rfc,c_rfc,wc_rfc=trainer(RFC,param, X, X_char, train, traintest, Y, y_test)

Random Forest Classifier
Accuracy of Word n-gram(1,6) : 0.7317784256559767
              precision    recall  f1-score   support

           0       0.70      0.86      0.77      1257
           1       0.79      0.59      0.68      1144

    accuracy                           0.73      2401
   macro avg       0.75      0.73      0.72      2401
weighted avg       0.74      0.73      0.73      2401

Best Parameters  {'n_estimators': 30}
Best Score  0.7317857142857143

Confusion Matrix
[[1082  175]
 [ 469  675]]

Accuracy of Char n-gram(1,8) : 0.7634319033735943
              precision    recall  f1-score   support

           0       0.75      0.83      0.79      1257
           1       0.78      0.69      0.74      1144

    accuracy                           0.76      2401
   macro avg       0.77      0.76      0.76      2401
weighted avg       0.77      0.76      0.76      2401

Best Parameters  {'n_estimators': 30}
Best Score  0.74625

Confusion Matrix
[[1039  218]
 [ 350  794]]

Accuracy of Combinining word & Char n-gram 0.7567680133277801
              precision    recall  f1-score   support

           0       0.74      0.83      0.78      1257
           1       0.79      0.67      0.73      1144

    accuracy                           0.76      2401
   macro avg       0.76      0.75      0.75      2401
weighted avg       0.76      0.76      0.75      2401

Best Parameters  {'n_estimators': 30}
Best Score  0.7526785714285714

Confusion Matrix
[[1047  210]
 [ 374  770]]

# Implementing Ensemble Hard voting

In [181]:
from sklearn.ensemble import VotingClassifier

In [182]:
vote_model = VotingClassifier(estimators=[('svcm', svc), ('MNBm', MNB), ('LRm', LR)], voting='hard')
param={}
w_ens,c_ens,wc_ens=trainer(vote_model,param, X, X_char, train, traintest, Y, y_test)

e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

Accuracy of Word n-gram(1,6) : 0.7663473552686381
              precision    recall  f1-score   support

           0       0.71      0.90      0.79      1191
           1       0.87      0.63      0.73      1210

    accuracy                           0.77      2401
   macro avg       0.79      0.77      0.76      2401
weighted avg       0.79      0.77      0.76      2401

Best Parameters  {}
Best Score  0.7260714285714286

Confusion Matrix
[[1073  118]
 [ 443  767]]

e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

Accuracy of Char n-gram(1,8) : 0.7721782590587255
              precision    recall  f1-score   support

           0       0.72      0.89      0.79      1191
           1       0.86      0.66      0.74      1210

    accuracy                           0.77      2401
   macro avg       0.79      0.77      0.77      2401
weighted avg       0.79      0.77      0.77      2401

Best Parameters  {}
Best Score  0.7764285714285715

Confusion Matrix
[[1059  132]
 [ 415  795]]

e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
e:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

Accuracy of Combinining word & Char n-gram 0.7809246147438568
              precision    recall  f1-score   support

           0       0.73      0.90      0.80      1191
           1       0.87      0.67      0.75      1210

    accuracy                           0.78      2401
   macro avg       0.80      0.78      0.78      2401
weighted avg       0.80      0.78      0.78      2401

Best Parameters  {}
Best Score  0.7839285714285714

Confusion Matrix
[[1068  123]
 [ 403  807]]